# Generated by Django 3.2 on 2021-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20210412_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='boss_id',
            field=models.ManyToManyField(null=True, to='Employee.Employee'),
        ),
    ]
