# Generated by Django 3.2 on 2021-04-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_boss_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='boss_id',
            field=models.ManyToManyField(related_name='_Employee_employee_boss_id_+', to='Employee.Employee'),
        ),
    ]
