# Generated by Django 3.2 on 2021-04-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_employee_boss_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank_level',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss_id',
            field=models.ManyToManyField(to='Employee.Employee'),
        ),
    ]
