# Generated by Django 3.2 on 2021-04-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_auto_20210415_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='expieance',
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank_level',
            field=models.CharField(choices=[('Newbie', 'Newbie'), ('Pubil', 'Pubil'), ('Specialist', 'Specialist'), ('Expert', 'Expert'), (' Candidate Master ', ' Candidate Master '), ('Master', 'Master'), ('Grandmaster', 'Grandmaster'), ('Legendary Grandmaster ', 'Legendary Grandmaster ')], max_length=30, null=True),
        ),
    ]
