# Generated by Django 3.2 on 2021-04-15 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0011_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='boss_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
