# Generated by Django 3.2 on 2021-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_auto_20210415_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='boss_id',
            field=models.ManyToManyField(related_name='_Employee_employee_boss_id_+', to='Employee.Employee'),
        ),
    ]
