# Generated by Django 3.2 on 2021-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_employee_boss_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='boss_id',
            field=models.ManyToManyField(to='Employee.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate_type',
            field=models.CharField(choices=[('Achivemant', 'Achivement'), ('Boss_rate', 'Boss_rate'), ('Time_rate', 'Time_rate')], max_length=12),
        ),
    ]
