# Generated by Django 3.2 on 2021-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_auto_20210416_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
