# Generated by Django 3.2 on 2021-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0017_alter_rating_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
