# Generated by Django 3.2 on 2021-04-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0019_complainte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complainte',
            new_name='complaint',
        ),
    ]
