# Generated by Django 3.2 on 2021-07-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0026_alter_complaint_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='date',
        ),
    ]
