# Generated by Django 3.2 on 2021-07-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0027_remove_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
