# Generated by Django 3.2 on 2021-08-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0029_rating_form_user_rate_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_expire', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating_form',
            name='hours_expire',
        ),
        migrations.RemoveField(
            model_name='rating_form',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='rating_form',
            name='Rate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.rate'),
        ),
        migrations.AddField(
            model_name='rating_form',
            name='form_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.form'),
        ),
    ]
