# Generated by Django 3.2 on 2021-08-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0032_alter_user_rate_form_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.notification')),
            ],
        ),
    ]
