# Generated by Django 3.2 on 2021-08-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0035_auto_20210816_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_notification',
            name='notification_id',
        ),
        migrations.AddField(
            model_name='user_notification',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_notification',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
