# Generated by Django 3.2 on 2021-08-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0036_auto_20210816_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rate',
            name='boss_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.user_rate_form'),
        ),
    ]
