# Generated by Django 3.2 on 2021-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0037_user_rate_boss_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rate_form',
            name='activation',
            field=models.IntegerField(default=1),
        ),
    ]
